### ISSUE TITLE
Upstream mtth/hdfs improvements

### ISSUE THREAD

**Issue by wesm** [cloudera/ibis#252]
Will list them here for tracking. 

- [x] mkdir (this request appears to be implemented, but it's not exposed as a public API, or tested for that matter)
- [x] download HDFS directory to local filesystem. (`Client.download` suggests that it has this functionality, but it's all lies)

**Comment by ihodes** [comment]
Adding make_directory here https://github.com/mtth/hdfs/pull/25

**Comment by mtth** [comment]
> `Client.download` suggests that it has this functionality, but it's all lies

Ouch. (Granted currently the name is misleading, but the doc does explicitly state its [use-case](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L469).)
You're right, that functionality would nice to have though. Will think about how best to go about it.

**Comment by wesm** [comment]
@mtth I implemented this in `ibis/filesystems.py`

**Comment by mtth** [comment]
Great, thanks, I'll take a look.

**Comment by mtth** [comment]
@wesm, @ihodes - Since `1.4.0`, [`Client.download`](http://hdfscli.readthedocs.org/en/latest/api.html#hdfs.client.Client.download) (and [`Client.upload`](http://hdfscli.readthedocs.org/en/latest/api.html#hdfs.client.Client.upload)) should do what you want; let me know if not. I plan on adding a callback hook for tracking progress when I next have some time.

**Comment by wesm** [comment]
thanks @mtth!
