### ISSUE TITLE
Add a conda recipe

### ISSUE THREAD

**Issue by wesm** [cloudera/ibis#382]
Such as:

https://github.com/pydata/pandas/tree/master/conda.recipe

**Comment by koverholt** [comment]
I created [conda packages for Ibis and its dependencies] (https://anaconda.org/koverholt) for `linux-64` and `osx-64`. You can conda install Ibis using:

```
conda install -c koverholt ibis-framework
```

I have the conda recipe files for ibis-framework and its dependencies if you would like me to open a PR and commit them somewhere.

You also might be interested in creating an account on [Anaconda.org] (http://www.anaconda.org) (e.g., named cloudera or ibis) so that you can maintain the conda packages and have users install from that channel using something like:

```
conda install -c cloudera ibis-framework
```

Let me know if I can help with any of those efforts.

**Comment by wesm** [comment]
Be happy to accept a PR — we'd probably need to set up a corporate CLA with Continuum that enumerates individual contributors

**Comment by wesm** [comment]
Nudging you about this, in case we can get it into the 0.4 release. Note that we're going to modify the  requirements (and remove snakebite, which is not used at all), so I may bug you to update the recipe once we do that

**Comment by koverholt** [comment]
Definitely, I can do that. Regarding the CLA, I should have something over to you by tomorrow.

**Comment by koverholt** [comment]
Update: Added list of contributors to the CLA on our side. Still waiting on the CLA to be signed off. Will get it to you as soon as that happens. Let me know if you need any updates in the mean time.

**Comment by koverholt** [comment]
I just sent a copy of the CLA to your email. Please let me know if you need any additional information. Thanks!
