### ISSUE TITLE
Array Datatype API and Operations

### ISSUE THREAD

**Issue by cpcloud** [cloudera/ibis#851]
We should enable basic operations on `ARRAY<T>` types after #848 is merged.
- `array.length()`: number of elements in each array in a column
- `array[start:stop]` and `array[index]`, i.e., `__getitem__`: element selection
- `array.collect`: collecting scalar values into an `GROUP BY`
- `array.contains(element)`: is `element` in `array`
- `array.concat(*arrays)`: concatenate `array` with `*arrays`
- `array.find(element)`: returns the index of the first occurrence of `element` and -1 if it's not found

Most of the work that needs to be done here is in the type system.

@wesm I've done a lot of this work, but in retrospect I think renaming `Array`-the-column to `Field` is a better in the long term to disambiguate it from `Array`-the-element-type. Otherwise we get things like `ArrayArray` (as opposed to `ArrayField`).

xref #782

**Comment by wesm** [comment]
Yeah, I think either Field or Column is a reasonable renaming -- one question is that there are `FooTypeValue` for scalar values so I am not sure the best way to connote a collection (maybe Column). I don't believe users will be impacted by this "API" change, since the class names were never explicitly part of the API.
