### ISSUE TITLE
Comparison with Blaze

### ISSUE THREAD

**Issue by arita37** [cloudera/ibis#896]
It sounds like a re-writing of Blaze project.
What are the differences with Blaze since Blaze performs quite well ?

**Comment by cpcloud** [comment]
There's a comparison at the end of this blog post: http://www.ibis-project.org/design-types-operations/.

Ibis is more ambitious with respect to SQL (window functions should work no matter what database you're using), and less ambitious with respect to the systems it can successfully operate on (seamless querying of HDF5 files isn't on the list of priorities).

**Comment by wesm** [comment]
@arita37 I think @cpcloud summarized it fairly well. There is functional overlap but quite different design goals. The Blaze DSL falls short in SQL compatibility, but what you can express can be evaluated on a more diverse set of systems. So we designed for a depth-first use case (Ibis targets SQL-based systems with deeper functionality -- from a SQL point of view) rather than breadth-first (many kinds of execution backends, with shallower functionality).

From https://github.com/blaze/blaze/blob/master/README.rst, "Blaze is a good way to inspect data living in a large database, perform a small but powerful set of operations to query that data, and then transform your results into a format suitable for your favorite Python tools."

Our goal is different: to provide a functionally comprehensive interface to the analytical functionality provided by a SQL-based system (e.g. Postgres, Impala, Redshift, etc.) and provide a composable DSL to allow you express complex analysis workflows that get pushed down into the target backend.
