### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by cpcloud** [cloudera/ibis#942]
We have some code that's lying around that looks like it's collecting dust. I think we should remove it, since it's likely not being used.

I think some things should not be supported for the foreseeable future, and some should be rewritten and supported as features.

- [x] Madlib -- It looks like this is providing an API for madlib UDFs. I'd be very surprised if this particular aspect of ibis saw much use. I think would be better as a separate library called ibis-madlib.
- [x] comms.pyx/pxd -- This appears to be v0 of a mechanism to efficiently communicate with impala using Cython. It looks like [hs2client](http://www.ibis-project.org/new-native-impala-hive-client/) is the replacment. 
- [x] server -- This feature is only tested on Python 2 and does not have much in the way of documentation. I say we remove it.
- [x] tasks -- Also only tested on Python 2 and missing some docs. I'm not entirely sure what the motivation for this part of ibis is. It looks like a task scheduling mechanism, which is interesting, but it also seems a bit out of scope for the project.
- [x] async queries -- ~~I could see this being interesting in the context of a more generic task scheduler such as dask, but I'm curious what the current use case is.~~
- [x] UDFs -- ~~I think we can support this as a first class feature of ibis, possibly using numba. Numba has improved its ability to generate custom IR, which gives a lot more room for libraries like ibis to experiment with creating bespoke intrinsics. The elephant in the room is our old friend strings, which seem unlikely to show up in numba without serious lobbying and lots of work upfront. For now, we should remove them, possibly with a plan to implement v2.0 of this feature. I have some ideas here that I will try to find time to spec out.~~

@wesm Curious to hear your thoughts here.

**Comment by wesm** [comment]
The comms/server/tasks code was part of a prototype to add embedded UDFs to Impala -- the work did not firm up, and the ad hoc columnar serialization / shared memory IPC preceded my involvement in the (much more general) Apache Arrow project. You can see some of that in https://github.com/cloudera/ibis/blob/master/ibis/comms.pyx#L323

Definitely fine to delete all that cruft. Same for MADLib. 

I'm interested in expanding UDF support -- it's somewhat complicated as the LLVM libraries must match in general -- so if Numba uses a different version of LLVM than the one used to build Impala, then the IR may be incompatible (at least, I think I tried using LLVM 3.7 IR with LLVM 3.3 and could not in the past). Most of what's there now is tools for exposing C++ UDFs as Ibis expression callable, and that's useful. 

General async queries we should leave, because otherwise `execute` will always block, so users who are writing an application that uses Ibis to run long-running queries will have to implement their own asynchronous query execution. It's not terribly complicated, but nice to have integrated with the rest of the library.

**Comment by cpcloud** [comment]
Moving this to 0.10 as it looks like we'll be able to get this in.
